# Generated by Django 5.0.14 on 2025-05-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('vencido', 'Vencido'), ('devuelto', 'Devuelto')], default='activo', max_length=10),
        ),
    ]
