# Generated by Django 5.0.14 on 2025-04-12 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('año_publicacion', models.PositiveIntegerField()),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.genero')),
            ],
        ),
    ]
