# Generated by Django 5.0.14 on 2025-05-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libro_existencias_libro_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
