# Generated by Django 5.0.14 on 2025-04-14 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_mfa_enabled_usuario_mfa_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='mfa_secret',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='mfa_verified',
        ),
    ]
